name: Chatify
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine: ^1.0.8
  bubble: null
  cached_network_image: 2.0.0-rc.1
  cloud_firestore: ^0.12.9+5
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.3.4
  firebase_auth: ^0.14.0+5
  firebase_messaging: 6.0.13
  firebase_storage: ^3.0.6
  flutter_bloc: ^4.0.1
  flutter_ringtone_player: ^2.0.0
  flutter_svg: ^0.19.0
  fluttertoast: ^7.1.1
  focused_menu: ^1.0.1
  font_awesome_flutter: null
  giphy_picker: ^1.0.6
  http: null
  image_picker: ^0.6.4
  intl: ^0.15.7
  material_design_icons_flutter: ^4.0.5755
  matrix_gesture_detector: ^0.1.0
  permission_handler: ^5.0.1+1
  photo_view: ^0.5.0
  popup_menu: ^1.0.5
  screenshot: ^0.2.0
  shared_preferences: ^0.5.3+4
  splash_screen_view: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_new.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - images/mimi1.gif
    - images/mimi2.gif
    - images/mimi3.gif
    - images/mimi4.gif
    - images/mimi5.gif
    - images/mimi6.gif
    - images/mimi7.gif
    - images/mimi8.gif
    - images/mimi9.gif

  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Courgette
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica-Bold-Font.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: NimbusMono
      fonts:
        - asset: fonts/nimbusmono-regular.otf
    - family: Modern
      fonts:
        - asset: fonts/modern.ttf
    - family: Neon
      fonts:
        - asset: fonts/neon/neon.otf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
